export const GET_REQUEST = "GET_REQUEST";
export const GET_REQUEST_SUCCESS = "GET_REQUEST_SUCCESS";
export const GET_REQUEST_FAILED = "GET_REQUEST_FAILED";

export const GET_POSTS = "GET_POSTS";
export const GET_POST = "GET_POST";

export const UPDATE_POST = "UPDATE_POST";

export const DELETE_POST = "DELETE_POST";


export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_SUCCESS = "GET_CREATE_REQUEST_SUCCESS";
export const CREATE_POST_FAILED = "GET_CREATE_REQUEST_FAILED";
