export const USER_REGISTER_POST = "USER_REGISTER_POST";
export const USER_REGISTER_POST_SUCCESS = "USER_REGISTER_POST_SUCCESS";
export const USER_REGISTER_POST_FAILED = "USER_REGISTER_POST_FAILED";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";