export const USER_ORDERS_POST = "USER_ORDERS_POST";
export const USER_ORDERS_POST_SUCCESS = "USER_ORDERS_POST_SUCCESS";
export const USER_ORDERS_POST_FAILED = "USER_ORDERS_POST_FAILED";

export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAILED = "GET_ORDERS_FAILED";

export const USER_REVIEW_POST = "USER_REVIEW_POST";
export const USER_REVIEW_POST_SUCCESS = "USER_REVIEW_POST_SUCCESS";
export const USER_REVIEW_POST_FAILED = "USER_REVIEW_POST_FAILED";